//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "interoplib.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_interoplib_interoplib_Utilities::NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_interoplib =
{
    "interoplib",
    0x6C400EF7,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
