//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "interoplib.h"
#include "interoplib_interoplib_WiFi.h"

using namespace interoplib::interoplib;


HRESULT Library_interoplib_interoplib_WiFi::NativeSetup___STATIC__VOID__STRING__STRING( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        const char* param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_LPCSTR( stack, 0, param0 ) );

        const char* param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_LPCSTR( stack, 1, param1 ) );

        WiFi::NativeSetup( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_interoplib_interoplib_WiFi::NativeConnect___STATIC__VOID__STRING__STRING( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        const char* param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_LPCSTR( stack, 0, param0 ) );

        const char* param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_LPCSTR( stack, 1, param1 ) );

        WiFi::NativeConnect( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_interoplib_interoplib_WiFi::NativeStop___STATIC__VOID( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        WiFi::NativeStop(  hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}
