//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "interoplib.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    Library_interoplib_interoplib_LedPixelController::NativeInit___STATIC__VOID__I4__I4__I4__I4__I4__U1__U1__U1,
    Library_interoplib_interoplib_LedPixelController::NativeWrite___STATIC__VOID__SZARRAY_U1,
    Library_interoplib_interoplib_LedPixelController::NativeSetFull___STATIC__VOID__U1__U1__U1,
    Library_interoplib_interoplib_LedPixelController::NativeSetPixel___STATIC__VOID__U1__U2__U1__U1__U1,
    NULL,
    NULL,
    Library_interoplib_interoplib_Utilities::NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1,
    NULL,
    NULL,
    NULL,
    Library_interoplib_interoplib_WiFi::NativeSetup___STATIC__VOID__STRING__STRING,
    Library_interoplib_interoplib_WiFi::NativeConnect___STATIC__VOID__STRING__STRING,
    Library_interoplib_interoplib_WiFi::NativeStop___STATIC__VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_interoplib =
{
    "interoplib",
    0xE121BE09,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
