//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef INTEROPLIB_H
#define INTEROPLIB_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_interoplib_interoplib_LedPixelController
{
    NANOCLR_NATIVE_DECLARE(NativeInit___STATIC__VOID__I4__I4__I4__I4__I4__U1__U1__U1);
    NANOCLR_NATIVE_DECLARE(NativeWrite___STATIC__VOID__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeSetFull___STATIC__VOID__U1__U1__U1);
    NANOCLR_NATIVE_DECLARE(NativeSetPixel___STATIC__VOID__U1__U2__U1__U1__U1);

    //--//
};

struct Library_interoplib_interoplib_Utilities
{
    static const int FIELD_STATIC___hardwareSerial = 0;

    NANOCLR_NATIVE_DECLARE(NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_interoplib;

#endif // INTEROPLIB_H
